### ISSUE TITLE
Comma doesn't need to be boldened. 

### ISSUE THREAD

**Issue by elfishhenry** [elfishhenry/WhatsThatWord#3]
![image](https://github.com/user-attachments/assets/e71adf30-a655-46bc-84f4-d953f0d7fa9f)
Comma after username doesn't need to be bold.

**Comment by lodenrogue** [comment]
Looks like the issue is here: https://github.com/elfishhenry/WhatsThatWord/blob/bcb20e05a115371d8a036a845134e11b6577384e/cogs/RTFD.py#L56

Probaby just need to move the ** before the word Choose to before the comma.

**Comment by elfishhenry** [comment]
Thanks, I've edited the command with some additional formatting.
